### ISSUE TITLE
better examples, how to use maintain() ?

### ISSUE THREAD

**Issue by Dravon5X** [UIPEthernet/UIPEthernet#24]
Hello

1. I see in code "maintain() must be called at regular intervals" but it's not used in any example. So how often maintain() should be called? Every loop() without delays (so millis and timer need to be used), or like every second or once per 10 minutes?

2. if I'm sending data with client.connect() every 5 minutes, is dns server every time asked to translate hostname to ip? if not, can you add this? as IP can be changed (like when using ddns).

3. examples in this library are not much friendly, I did not found simple way how to send GET or POST to web site. Maybe you can add this one?
http://arduinotronics.blogspot.sk/2015/12/sending-sensor-data-to-web-server.html
I believe sending data from arduino via POST to web site is much more needed than "advanced chat server"

**Comment by jandrassy** [comment]
maintain() checks DHCP lease time and calls a renew if the lease timed out. so if the sketch uses DHCP it shoud call it once in loop() even if the loop is 'slow' with long time taking functions or delays.

BUT if the sketch doesn't call any function of the UIPEthernet library for a long time*, the library can't handle the network traffic. In this case calling maintain() is good as calling any other function of the library.

so instead of delay(30000) use
```
for (int i = 0; i < 30; i++) {
  delay(1000);
  Ethernet.maintain();
}
```

* 10 seconds are a long time in a silent network. in network with a lot of traffic 3 seconds is a long time
